language: generic

# required to install tools on Linux
sudo: required

branches:
  only:
  - develop

install:
    # install latest release version of hugo
    - wget https://github.com/gohugoio/hugo/releases/download/v0.75.1/hugo_0.75.1_Linux-64bit.deb
    - sudo dpkg -i hugo_0.75.1_Linux-64bit.deb

script:
    - hugo

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  verbose: true
  keep-history: true
  local-dir: public
  target-branch: master
  on:
    branch: develop